#%RAML 1.0 DataType
properties:
        itemNumber:
          type: string
          required: true
          example: "101"
        itemName:
          type: string
          required: true
          example: "Iphone 13"
        price:
          type: string
          required: true
          example: "120000"
        warranty:
          type: string
          required: true
          example: "1 year"